
#!/bin/bash

root -l -b -q stack_Approval.cpp'("fEleEtaLead","anaEMu", 10, -5, 5, "")'
root -l -b -q stack_Approval.cpp'("fdEtaAtVtxLead","anaEMu", 20, -0.01, 0.01, "")'
root -l -b -q stack_Approval.cpp'("fdPhiAtVtxLead","anaEMu", 20, -0.05, 0.05, "")'
root -l -b -q stack_Approval.cpp'("fSigmaIEtaIEtaLead","anaEMu", 20, 0, 0.05, "")'
root -l -b -q stack_Approval.cpp'("fHoverELead","anaEMu", 20, 0, 0.05, "")'
root -l -b -q stack_Approval.cpp'("fDxyLead","anaEMu", 20, -0.05, 0.05, "")'
root -l -b -q stack_Approval.cpp'("fDzLead","anaEMu", 20, -0.5, 0.5, "")'
root -l -b -q stack_Approval.cpp'("fEoverPInvLead","anaEMu", 50, 0., .3, "")'
root -l -b -q stack_Approval.cpp'("fMissHitsLead","anaEMu", 10, -0.5, 9.5, "")'
root -l -b -q stack_Approval.cpp'("fConversionVetoLead","anaEMu", 2, -0.5, 1.5, "")'

root -l -b -q stack_Approval.cpp'("fEleEtaLead","anaEleEle", 10, -5, 5, "")'
root -l -b -q stack_Approval.cpp'("fdEtaAtVtxLead","anaEleEle", 20, -0.01, 0.01, "")'
root -l -b -q stack_Approval.cpp'("fdPhiAtVtxLead","anaEleEle", 20, -0.05, 0.05, "")'
root -l -b -q stack_Approval.cpp'("fSigmaIEtaIEtaLead","anaEleEle", 20, 0, 0.05, "")'
root -l -b -q stack_Approval.cpp'("fHoverELead","anaEleEle", 20, 0, 0.05, "")'
root -l -b -q stack_Approval.cpp'("fDxyLead","anaEleEle", 20, -0.05, 0.05, "")'
root -l -b -q stack_Approval.cpp'("fDzLead","anaEleEle", 20, -0.5, 0.5, "")'
root -l -b -q stack_Approval.cpp'("fEoverPInvLead","anaEleEle", 50, 0., .3, "")'
root -l -b -q stack_Approval.cpp'("fMissHitsLead","anaEleEle", 10, -0.5, 9.5, "")'
root -l -b -q stack_Approval.cpp'("fConversionVetoLead","anaEleEle", 2, -0.5, 1.5, "")'

root -l -b -q stack_Approval.cpp'("fEleEtaSublead","anaEleEle", 10, -5, 5, "")'
root -l -b -q stack_Approval.cpp'("fdEtaAtVtxSublead","anaEleEle", 20, -0.01, 0.01, "")'
root -l -b -q stack_Approval.cpp'("fdPhiAtVtxSublead","anaEleEle", 20, -0.05, 0.05, "")'
root -l -b -q stack_Approval.cpp'("fSigmaIEtaIEtaSublead","anaEleEle", 20, 0, 0.05, "")'
root -l -b -q stack_Approval.cpp'("fHoverESublead","anaEleEle", 20, 0, 0.05, "")'
root -l -b -q stack_Approval.cpp'("fDxySublead","anaEleEle", 20, -0.05, 0.05, "")'
root -l -b -q stack_Approval.cpp'("fDzSublead","anaEleEle", 20, -0.5, 0.5, "")'
root -l -b -q stack_Approval.cpp'("fEoverPInvSublead","anaEleEle", 50, 0., .3, "")'
root -l -b -q stack_Approval.cpp'("fMissHitsSublead","anaEleEle", 10, -0.5, 9.5, "")'
root -l -b -q stack_Approval.cpp'("fConversionVetoLead","anaEleEle", 2, -0.5, 1.5, "")'